### ISSUE TITLE
invalid API request body

### ISSUE THREAD

**Issue by brignano** [byAniket/cliams#8]
Can you please confirm the request parameters and their valid values as per the backend?

One thing I noticed is that the current request body appears to be rejected by the API.

## Current Request Body
```json
{
    "policyNum": "123456",
    "type": "",
    "description": "testing"
}
```

## Current API Response
```json
{
    "message": "Invalid request body"
}
```

Based on a lucky first guess, it looks like the API might be expecting `policyNumber` instead of `policyNum`?

## Updated Request Body
```json
{
    "policyNumber": "123456",
    "type": "",
    "description": "testing"
}
```

## Updated API Response
```json
{
    "errorType": "string",
    "errorMessage": "400 - Invalid Input",
    "trace": []
}
```

Now it looks like I'm sending a valid request body (using `policyNumber`) but it has some invalid input.

My guess is that this is due to the request missing `"type": ""` or having something invalid format for `"policyNumber": "123456"` (i.e. invalid length) but I'm not sure exactly what is expected by the API.

**Comment by mattkoser** [comment]
Hey there, 

The API wants an integer for policyNum, and a type in a certain list.

{
    "policyNum": 123456,
    "type": "collision",
    "description": "testing"
}

This will go through and return a uid. I will add some more clear callbacks.  If this is a problem, let me know and I can fix it.
